name: Code Quality Check

on:
  push:
    branches: ['*'] # すべてのブランチに対してpushが発生したとき実行
  pull_request:
    branches: ['*'] # すべてのブランチへのプルリクエストで実行
  workflow_dispatch:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Create ESLint config if not exists
        run: |
          if [ ! -f eslint.config.js ]; then
            echo 'import globals from "globals";
            import js from "@eslint/js";
            import prettier from "eslint-plugin-prettier/recommended";

            export default [
              js.configs.recommended,
              {
                languageOptions: {
                  globals: {
                    ...globals.browser
                  },
                  ecmaVersion: 2022,
                  sourceType: "module"
                },
                rules: {
                  "no-unused-vars": "warn",
                  "no-undef": "error",
                  "semi": ["error", "always"],
                  "indent": ["error", 2]
                }
              },
              prettier
            ];' > eslint.config.js
          fi

      - name: Create Stylelint config if not exists
        run: |
          if [ ! -f .stylelintrc.json ]; then
            echo '{
              "extends": "stylelint-config-standard",
              "rules": {
                "indentation": 2,
                "color-hex-case": "lower",
                "color-hex-length": "short"
              }
            }' > .stylelintrc.json
          fi

      - name: Create HTML Validate config if not exists
        run: |
          if [ ! -f .htmlvalidate.json ]; then
            echo '{
              "extends": ["html-validate:recommended"],
              "rules": {
                "element-required-attributes": "error",
                "void-style": "off"
              }
            }' > .htmlvalidate.json
          fi

      - name: Lint JavaScript
        run: npm run lint:js || npx eslint "*.js" --fix

      - name: Lint CSS
        run: npm run lint:css || npx stylelint "*.css" --fix

      - name: Validate HTML
        run: npm run lint:html || npx html-validate "*.html"
